tap "cjbassi/gotop"
tap "esimov/triangle"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
brew "ack"
brew "archey"
brew "openssl"
brew "aria2"
brew "autoconf"
brew "automake"
brew "bamtools"
brew "bash"
brew "bash-completion"
brew "bash-snippets"
brew "bat"
brew "bench"
brew "bork"
brew "cabextract"
brew "freetype"
brew "gettext"
brew "readline"
brew "pixman"
brew "cairo"
brew "calc"
brew "ccrypt"
brew "cloc"
brew "cmake"
brew "coreutils"
brew "cowsay"
brew "cscope"
brew "ctags"
brew "diff-so-fancy"
brew "elinks"
brew "exa"
brew "exiftool"
brew "faac"
brew "fd"
brew "flac"
brew "gmp"
brew "libunistring"
brew "nettle"
brew "gnutls"
brew "lame"
brew "little-cms2"
brew "xvid"
brew "ffmpeg"
brew "findutils"
brew "fortune"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gd"
brew "geoip"
brew "pcre2"
brew "git"
brew "git-lfs"
brew "git-secrets"
brew "gnuplot"
brew "go"
brew "grep"
brew "hdf5"
brew "htop"
brew "imagemagick"
brew "lynx"
brew "mas"
brew "moreutils"
brew "mysql"
brew "ncdu"
brew "ninja"
brew "nmap"
brew "openssh"
brew "pandoc"
brew "pkg-config"
brew "ripgrep"
brew "rsync"
brew "ruby"
brew "shellcheck"
brew "speedtest-cli"
brew "streamlink"
brew "textql"
brew "tmux"
brew "tokei"
brew "trash"
brew "tree"
brew "triangle"
brew "vim"
brew "wget"
brew "wine"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
brew "cjbassi/gotop/gotop"
brew "jesseduffield/lazydocker/lazydocker"
cask "alfred"
cask "arduino"
cask "balenaetcher"
cask "bettertouchtool"
cask "cheatsheet"
cask "cleanmymac"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "flux"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "iina"
cask "jupyter-notebook-viewer"
cask "malwarebytes"
cask "mendeley"
cask "processing"
cask "skype"
cask "spotify"
cask "steam"
cask "telegram"
cask "zenmap"
mas "1Password 7", id: 1333542190
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Agenda", id: 1287445660
mas "Keka", id: 470158793
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Shazam", id: 897118787
mas "Spark", id: 1176895641
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
