# ~/.zshrc
export EDITOR="vim"
export TERM="xterm-256color"
export PATH=$HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

# Adding locations with important executables to PATH
export PATH="/opt/homebrew/bin:$PATH"                             # Add homebrew bin to the PATH (to get 'brew')
export PATH="/opt/homebrew/sbin:$PATH"                            # Add homebrew sbin to the PATH (for some recipes)
export PATH="$PATH:/usr/local/texlive/2025/bin/universal-darwin"  # Add LaTeX installation to PATH (update when updating texlive!)
export PATH="$PATH:$HOME/.local/bin"                              # Add local tools (incl. claude etc) to the PATH
export PATH="$PATH:$HOME/.cargo/bin"                              # Add cargo binaries to the PATH
export PATH="$PATH:$HOME/.juliaup/bin"                            # Add juliaup managed installs to the PATH

# Shell customization
source "$HOME/dotfiles/zsh/printfuncs.sh"   # display functions for status updates
source "$HOME/dotfiles/zsh/utilities.sh"    # miscellaneous utility functions
source "$HOME/dotfiles/zsh/updates.sh"      # homebrew and system update functions
source "$HOME/dotfiles/zsh/aliases.sh"      # Plenty of QoL aliases
source "$HOME/dotfiles/zsh/pyfuncs.sh"      # Python virtual environment functions
source "$HOME/dotfiles/zsh/dockerfuncs.sh"  # docker utility functions
source "$HOME/dotfiles/zsh/mambasetup.sh"   # conda setup and prepending miniforge to PATH

# Getting the rustup shell setup
source "$HOME/.cargo/env"

# Explicitely give locations for these program configs
export CONDARC="$HOME/.config/conda/condarc"          # avoids having ~/.condarc
export IPYTHONDIR="$HOME/.config/ipython"             # avoids having ~/.ipython
export JUPYTER_CONFIG_DIR="$HOME/.config/jupyter"     # avoids having ~/.jupyter
export LESSHISTFILE="$HOME/.config/lesshst"           # avoids having ~/.lesshst
export MPLCONFIGDIR="$HOME/.config/matplotlib"        # avoids having ~/.matplotlib
export npm_config_cache="$HOME/.cache/npm"            # avoids having ~/.npm
export PYTHON_HISTORY="$HOME/.config/python/history"  # avoids having ~/.python_history

# Let uv know to use its own managed Python versions
# and to always compile bytecode when installing
export UV_PYTHON_PREFERENCE="only-managed"
export UV_COMPILE_BYTECODE=1

# Using GNUPG encryption
export GPG_TTY=$(tty)
gpgconf --launch gpg-agent

# For bat to allow mouse scrolling
export BAT_PAGER="less -RF"

# Activate ZSH Completions, and make them go to .cache/zsh
ZSH_COMPDUMP_DIR="$HOME/.cache/zsh"
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/bit bit

# Load Pluging Manager and let it handle the plugins
source "$HOME"/dotfiles/zsh/oh_my_zsh_settings.sh

# Start Starship for prompt customization
eval "$(starship init zsh)"

# This keeps showing up when it is also in ~/.cache/zsh
if [ -f "$HOME/.zcompdump" ]; then
    rm "$HOME/.zcompdump"
fi

# This keeps showing up when I never want it
if [ -f "$HOME/.viminfo" ]; then
    rm "$HOME/.viminfo"
fi
