# ~/.zshrc
export TERM="xterm-256color"
export PATH=$HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export EDITOR="vim"


# Adding places with executables to PATH
export PATH="/opt/homebrew/bin:$PATH"                             # Add homebrew bin to the PATH (to get 'brew')
export PATH="/opt/homebrew/sbin:$PATH"                            # Add homebrew sbin to the PATH (for some recipes)
export PATH="$PATH:/usr/local/texlive/2024/bin/universal-darwin"  # Add Tex installation to PATH
export PATH="$PATH:$HOME/.cargo/bin"                              # Add cargo binaries to the PATH
export PATH="$PATH:$HOME/.local/bin"                              # Add uv tools location to the PATH

# Shell customization
source "$HOME"/dotfiles/zsh/aliases.sh     # Plenty of QoL aliases 
source "$HOME"/dotfiles/zsh/functions.sh   # user-made functions
source "$HOME"/dotfiles/zsh/dockerfunc.sh  # docker utility functions
source "$HOME"/dotfiles/zsh/tmux.sh        # tmux manipulation aliases and functions


# Load Pluging Manager
source "$HOME"/dotfiles/zsh/oh_my_zsh_settings.sh
#source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
#antidote load


# Using GNUPG encryption
export GPG_TTY=$(tty)
gpgconf --launch gpg-agent

# For bat to allow mouse scrolling
export BAT_PAGER="less -RF"

# Activate ZSH Completions
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/bit bit


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/felixsoubelet/.miniforge/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/felixsoubelet/.miniforge/etc/profile.d/conda.sh" ]; then
        . "/Users/felixsoubelet/.miniforge/etc/profile.d/conda.sh"
    else
        export PATH="/Users/felixsoubelet/.miniforge/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/Users/felixsoubelet/.miniforge/etc/profile.d/mamba.sh" ]; then
    . "/Users/felixsoubelet/.miniforge/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<


# Start Starship for prompt customization
eval "$(starship init zsh)"

. "$HOME/.cargo/env"
